const CATEGORIES = {
  stage: "ステージ",
  exhibit: "展示",
  experience: "体験",
  food: "飲食",
  lab: "研究室公開",
};

const PROJECTS = [
  { id: "p01", cat: "stage", name: "軽音楽部ライブ", org: "軽音楽部", place: "第一体育館", time: "両日 11:00 / 14:00", desc: "部内バンドによる年に一度の本気のステージ。" },
  { id: "p02", cat: "stage", name: "吹奏楽部定期演奏会", org: "吹奏楽部", place: "第一体育館", time: "11/1 (日) 10:15", desc: "ポップスから映画音楽まで、聴きなじみのある曲を中心に。" },
  { id: "p03", cat: "stage", name: "ダンスパフォーマンス", org: "ダンス同好会", place: "中庭 野外ステージ", time: "両日 13:00", desc: "1年生から専攻科生まで総勢20名のショーケース。" },
  { id: "p04", cat: "stage", name: "のど自慢大会", org: "学生会", place: "第一体育館", time: "10/31 (土) 15:00", desc: "飛び入り参加歓迎。優勝者には豪華賞品あり。" },
  { id: "p05", cat: "stage", name: "ビンゴ大会", org: "学生会", place: "第一体育館", time: "11/1 (日) 15:00", desc: "電波祭のフィナーレ。景品は家電からお菓子まで。" },
  { id: "p06", cat: "exhibit", name: "ロボコンマシン展示・実演", org: "ロボット研究部", place: "実習工場", time: "両日 10:00-16:00", desc: "全国大会出場マシンの実演走行は毎時00分から。" },
  { id: "p07", cat: "exhibit", name: "写真部作品展", org: "写真部", place: "講義棟 2F", time: "両日 10:00-16:00", desc: "テーマは「島と海」。三豊の風景を集めました。" },
  { id: "p08", cat: "exhibit", name: "鉄道模型ジオラマ運転会", org: "鉄道研究同好会", place: "講義棟 1F", time: "両日 10:00-16:00", desc: "運転体験もできます(小学生以下優先)。" },
  { id: "p09", cat: "exhibit", name: "美術部イラスト展", org: "美術部", place: "講義棟 2F", time: "両日 10:00-16:00", desc: "部員の原画展示と似顔絵コーナー。" },
  { id: "p10", cat: "experience", name: "アマチュア無線公開運用", org: "無線部", place: "電子棟 屋上", time: "両日 10:00-15:00", desc: "電波祭の名にかけて。海外との交信に挑戦しよう。" },
  { id: "p11", cat: "experience", name: "プログラミングでゲームを作ろう", org: "情報工学科 有志", place: "情報棟 演習室", time: "両日 10:30 / 13:30", desc: "小中学生向けの60分ワークショップ。予約優先。" },
  { id: "p12", cat: "experience", name: "eスポーツ大会", org: "eスポーツ同好会", place: "情報棟 1F", time: "両日 10:00-16:00", desc: "自由参加のオープントーナメント。観戦だけでも。" },
  { id: "p13", cat: "experience", name: "電子工作教室", org: "電子システム工学科 有志", place: "電子棟 実験室", time: "両日 11:00 / 14:00", desc: "はんだ付けでLEDバッジを作ります。材料費200円。" },
  { id: "p14", cat: "experience", name: "お化け屋敷「圏外」", org: "3年有志", place: "講義棟 3F", time: "両日 10:00-16:00", desc: "電波の届かない場所で、何かが起きる。" },
  { id: "p15", cat: "food", name: "焼きそば", org: "バレーボール部", place: "中庭 屋台エリア", time: "両日 10:00-15:00", desc: "鉄板2枚体制でお待ちしています。400円。" },
  { id: "p16", cat: "food", name: "からあげ", org: "野球部", place: "中庭 屋台エリア", time: "両日 10:00-15:00", desc: "揚げたて。塩・のり塩・ピリ辛の3種。" },
  { id: "p17", cat: "food", name: "クレープ", org: "茶道部", place: "中庭 屋台エリア", time: "両日 10:00-15:00", desc: "定番チョコバナナから季節の限定まで。" },
  { id: "p18", cat: "food", name: "うどん", org: "香川県人会", place: "学生食堂", time: "両日 10:00-15:00", desc: "香川に来たからには。かけ・ぶっかけ 300円。" },
  { id: "p19", cat: "food", name: "たこ焼き", org: "サッカー部", place: "中庭 屋台エリア", time: "両日 10:00-15:00", desc: "外カリ中トロ。8個入り400円。" },
  { id: "p20", cat: "lab", name: "通信ネットワーク工学科 体験ツアー", org: "通信ネットワーク工学科", place: "通信棟", time: "両日 10:30 / 13:00 / 15:00", desc: "アンテナ実験室と電波暗室を見学できます。" },
  { id: "p21", cat: "lab", name: "電子システム工学科 研究室公開", org: "電子システム工学科", place: "電子棟", time: "両日 10:00-16:00", desc: "パワーエレクトロニクスからセンサまで6研究室が公開。" },
  { id: "p22", cat: "lab", name: "情報工学科 デモ展示", org: "情報工学科", place: "情報棟", time: "両日 10:00-16:00", desc: "VR・画像認識・生成AIのデモを体験できます。" },
];

const STAGE_EVENTS = [
  { day: 1, venue: "main", start: "10:00", end: "10:10", title: "開会式", org: "学生会" },
  { day: 1, venue: "main", start: "10:15", end: "11:00", title: "吹奏楽部ステージ", org: "吹奏楽部" },
  { day: 1, venue: "main", start: "11:00", end: "12:00", title: "軽音楽部ライブ 1st", org: "軽音楽部" },
  { day: 1, venue: "main", start: "13:00", end: "14:00", title: "研究発表ステージ", org: "専攻科" },
  { day: 1, venue: "main", start: "14:00", end: "15:00", title: "軽音楽部ライブ 2nd", org: "軽音楽部" },
  { day: 1, venue: "main", start: "15:00", end: "16:00", title: "のど自慢大会", org: "学生会" },
  { day: 1, venue: "open", start: "10:30", end: "11:30", title: "アコースティックライブ", org: "軽音楽部" },
  { day: 1, venue: "open", start: "13:00", end: "13:45", title: "ダンスパフォーマンス", org: "ダンス同好会" },
  { day: 1, venue: "open", start: "14:30", end: "15:30", title: "大道芸パフォーマンス", org: "ジャグリング同好会" },
  { day: 2, venue: "main", start: "10:15", end: "11:00", title: "吹奏楽部定期演奏会", org: "吹奏楽部" },
  { day: 2, venue: "main", start: "11:00", end: "12:00", title: "軽音楽部ライブ 1st", org: "軽音楽部" },
  { day: 2, venue: "main", start: "13:00", end: "14:00", title: "クイズ大会", org: "学生会" },
  { day: 2, venue: "main", start: "14:00", end: "15:00", title: "軽音楽部ライブ 2nd", org: "軽音楽部" },
  { day: 2, venue: "main", start: "15:00", end: "15:45", title: "ビンゴ大会", org: "学生会" },
  { day: 2, venue: "main", start: "15:45", end: "16:00", title: "閉会式", org: "学生会" },
  { day: 2, venue: "open", start: "10:30", end: "11:30", title: "カラオケ大会", org: "学生会" },
  { day: 2, venue: "open", start: "13:00", end: "13:45", title: "ダンスパフォーマンス", org: "ダンス同好会" },
  { day: 2, venue: "open", start: "14:00", end: "15:00", title: "お笑いライブ", org: "落語研究会" },
];

const NEWS = [
  { date: "10.02", text: "パンフレットPDFを公開しました", href: "goods.html" },
  { date: "09.18", text: "ステージタイムテーブルを更新しました", href: "timetable.html" },
  { date: "09.10", text: "シャトルバスの運行情報を掲載しました", href: "access.html" },
  { date: "09.01", text: "電波祭公式サイトをオープンしました", href: "news.html" },
];
